SCREEN_WIDTH = 1980
SCREEN_HEIGHT = 1080

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.2# seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 450
PLAYER_SPEED = 300
PLAYER_SHOOT_SPEED = 1200
PLAYER_SHOOT_COOLDOWN = 0.15

SHOT_RADIUS = 5

